### ISSUE TITLE
Non-matrix form is not working

### ISSUE THREAD

**Issue by francoisschwarzentruber** [fusion809/simplex#2]
Non-matrix form on 

```
Maximize G = 000.1x1 + 0.01x2 + 0.1x3 + x4
	Subject to:
	x1 ≤ 1
	0.2x1 + x2 ≤ 1
	0.02x1 +0.2x2 + x3 ≤ 1
	0.002x1 + 0.02x2 + 0.2x3 + x4 ≤ 1
```

is not working.

The error is:

```
Object { name: "InvalidParameter", stack: "e@https://unpkg.com/mathjs@7.5.1/dist/math.min.js:42:85\nb@https://unpkg.com/mathjs@7.5.1/dist/math.min.js:42:398\nr@https://unpkg.com/mathjs@7.5.1/dist/math.min.js:42:1007\nc@https://unpkg.com/mathjs@7.5.1/dist/math.min.js:42:1938\nstring@https://unpkg.com/mathjs@7.5.1/dist/math.min.js:42:105339\ne@https://unpkg.com/mathjs@7.5.1/dist/math.min.js:42:47485\nfracToDecimal@https://fusion809.github.io/simplex/fractions.js:25:25\naddConstrToArr@https://fusion809.github.io/simplex/readNonMat.js:45:33\nreadNonMatForm@https://fusion809.github.io/simplex/readNonMat.js:403:25\ngetParameters@https://fusion809.github.io/simplex/readInputs.js:59:13\nsolveProblem@https://fusion809.github.io/simplex/simplex.js:201:58\nonclick@https://fusion809.github.io/simplex/:1:1\n", message: "" }
```

**Comment by fusion809** [comment]
Thank you for your error report. Problem is that I cannot seem to reproduce your error. I copy-pasted your problem into the non-matrix form box, clicked the option for "Use non-matrix format?" and then clicked the button to solve the problem and it worked with no error. Could you please tell me which web browser you are using?

**Comment by francoisschwarzentruber** [comment]
I am using Firefox.

**Comment by francoisschwarzentruber** [comment]
I do not understand; it works on my computer too now. That is crazy!

**Comment by fusion809** [comment]
Yeah, I just tried it in Firefox and the error didn't occur. Not sure how to fix this error if I can't reproduce it.

**Comment by fusion809** [comment]
Of course if you can provide information on how to reproduce this bug, I will do my best to debug it.

**Comment by francoisschwarzentruber** [comment]
Sorry I am unable to reproduce the error :/.
